routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Public
Route::get('/', 'PublicController@index')->name('index');
Route::get('/brand', 'PublicController@brand')->name('brand');
Route::get('/contact', 'PublicController@contact')->name('contact');
Route::post('/contact', 'PublicPostController@contact')->name('contactPost');
Route::get('/faq', 'PublicController@faq')->name('faq');
Route::get('/privacy-policy', 'PublicController@pp')->name('pp');
Route::get('/terms-and-conditions', 'PublicController@tac')->name('tac');
Route::get('/claims-and-returns', 'PublicController@car')->name('car');

// Cart
Route::prefix('cart')->name('cart.')->group(function() {
    Route::get('/', 'CartController@index')->name('index');
    Route::post('/add', 'CartController@add')->name('add');
    Route::get('/remove/{id}', 'CartController@remove')->name('remove');
});

// Orders
Route::resource('orders', 'OrderController')->only([
    'create', 'store'
]);
Route::get('/orders/{order}/payment', 'OrderController@payment')->name('orders.payment');
Route::get('/orders/{order}/pay/{paypal_id}', 'OrderController@pay')->name('orders.pay');
//Route::get('/orders/{order}/gen', 'OrderController@generateInvoice');

// Products
Route::prefix('products')->name('products.')->group(function() {
    Route::get('/', 'ProductController@index')->name('index');
//    Route::get('/t-shirt/{product}/{color}/{size}', 'ProductController@show')->name('product');
    Route::get('/t-shirt/old/{color}/{size}', 'ProductController@old')->name('old');
    Route::get('/t-shirt/sober/{color}/{size}', 'ProductController@sober')->name('sober');
    Route::get('/t-shirt/set/{size}', 'ProductController@set')->name('set');
});

// Auth, Account & Admin
Auth::routes();
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('fb');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback')->name('fb_callback');

Route::prefix('account')->name('account.')->middleware('auth')->group(function() {
    Route::get('/', 'AccountController@index')->name('index');
    Route::put('/update', 'AccountController@update')->name('update');
    Route::get('/download', 'AccountController@download')->name('download');
    Route::post('/delete', 'AccountController@delete')->name('delete');

    Route::resource('orders', 'OrderController')->only([
        'index', 'show'
    ]);
    Route::get('/orders/{order}/invoice', 'OrderController@invoice')->name('orders.invoice');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'check-admin'])->group(function() {
    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('comments', 'Admin\CommentController')->only([
        'store'
    ]);

    Route::resource('orders', 'Admin\OrderController')->only([
        'index', 'show'
    ]);
    Route::get('/orders/{order}/invoice', 'Admin\OrderController@invoice')->name('orders.invoice');
    Route::put('/orders/{order}/status', 'Admin\OrderController@status')->name('orders.status');

    Route::resource('users', 'Admin\UserController')->only([
        'index', 'show', 'edit', 'update'
    ]);
});

resources/views/brand.blade.php
@extends('layouts.public')

@section('title', 'Brand - ' . config('app.name'))

@section('content')
    <div id="page-content">
        <div class="container pt-2 pt-lg-5 pb-5">
            <h1>@lang('brand.title')</h1>

            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">
                    <p class="text-center big-icon mb-0">@fa('tshirt')</p>

                    <p class="text-center lead"><span class="h2 color-first font-primary">For This Shi(r)t</span><br> @lang('brand.1')</p>

                    <hr class="part first">

                    <p>@lang('brand.2')</p>

                    <div class="row">
                        <div class="col-12 col-lg-6">
                            <img src="{{ mix('images/tshirts/old/1_800x600.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail mb-2 mb-lg-0" alt="">
                        </div>

                        <div class="col-12 col-lg-6">
                            <img src="{{ mix('images/tshirts/sober/1_800x600.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail" alt="">
                        </div>
                    </div>

                    <p class="mt-2">@lang('brand.3')</p>

                    <div class="text-center pb-2">
                        <a href="{{ route('products.index') }}" class="btn btn-first btn-lg">@lang('products/index.all')</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/car.blade.php
@extends('layouts.public')

@section('title', 'Claims & returns - ' . config('app.name'))

@section('content')
    <div id="page-content">
        <div class="container pt-2 pt-lg-5 pb-5">
            <h1>Claims & returns</h1>

            <p>Last updated: 16.9.2019</p>

            <h2 class="color-first">Complaint conditions</h2>

            <ol>
                <li>The customer must visually inspect the goods immediately upon receipt. He shall be entitled not to accept the goods if there is visible mechanical damage obviously due to the transport or if the goods are incomplete. If the complaint is made within 7 days from the date of delivery, Yasmin Trade s.r.o. undertakes to replace the damaged goods. Following the possible recurrence of this case, Yasmin Trade s.r.o. allows the customer to cancel the order. Delayed claims of this type will not be Yasmin Trade s.r.o. accept and will deal with them as a normal claim referred to in point 2.</li>

                <li>If a claim is made later, the usual claim procedure set out in Yasmin Trade s.r.o. In the event of a claim, the customer may contact Yasmin Trade s.r.o. by telephone (+421 911 415 992), by e-mail (fts@yasmin-trade.com) or by post. The place of complaint is the registered office of Yasmin Trade s.r.o. (Na vŕšku 6, 811 01, Bratislava, Slovak Republic). When making a claim, the customer is obliged to deliver the claimed goods in the original packaging, including a copy of the delivery note or invoice. All goods sold are covered by the statutory warranty period, which is specified in the warranty card delivered with the goods, unless otherwise stated for the goods.</li>

                <li>After receiving the goods together with the complaint we are obliged within 30 days in writing by e-mail, respectively. registered letter to inform you about the result of the complaint procedure.</li>

                <li>If the claim is recognized, you have the right to exchange the defective goods for a new one or a refund.</li>

                <li>In case of unjustified complaint, the customer is obliged to pay the costs incurred in resolving this complaint.</li>

                <li>The warranty becomes void if the defect was caused by mechanical damage to the product (misuse) on the buyer's side.</li>
            </ol>

            <p>If the claim is justified, the buyer has the right to:</p>

            <ul>
                <li>to replace the product for a new one or to withdraw from the contract (refund the purchase price by credit note) if it is an irremovable defect or removable defects repeatedly irrespective of their type and prevents the product from being used for its intended purpose (the buyer has the right choose between replacing a product or returning the purchase price - it can't change its choice subsequently)</li>

                <li>in the event of a replacement, the warranty period shall commence again upon receipt of the new product</li>
            </ul>

            <h2 class="color-first">Returns within 14 days</h2>

            <ul>
                <li>The customer of the e-shop has the right to withdraw from the order without giving a reason within 14 days of receipt of the goods. If you purchase the goods in connection with your business (the invoice includes the identification number), the right of withdrawal does not arise.</li>

                <li>Goods can be returned personally in our store or mailed to Yasmin Trade s.r.o., Na vŕšku 6, 811 01, Bratislava, Slovak Republic.</li>

                <li>The returned goods must be unused, in their original condition and packaging as if they were taken over. Proof of purchase is also required.</li>

                <li>Do not send the goods cash on delivery, as such shipment will not be received. We recommend sending the goods by registered mail and insuring it.</li>

                <li>Please tell us at fts@yasmin-trade.com that you are shipping the goods back - please include your order number.</li>

                <li>Upon receipt of the goods, we will inspect it and inform you by e-mail about the expected date of equipment.</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/cart.blade.php
@extends('layouts.public')

@section('title', 'Cart - ' . config('app.name'))

@section('content')
    <div id="page-content">
        <div class="container pt-2 pt-lg-5 pb-5">
            <h1>@lang('cart.title')</h1>

            @if($objCart->count() == 0)
                <div class="text-center">
                    <p class="big-icon">@fa('shopping-cart')</p>

                    <p class="lead">@lang('cart.empty')</p>

                    <a href="{{ route('products.index') }}" class="btn btn-first btn-lg">@lang('products/index.all')</a>
                </div>
            @else
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>@lang('cart.product')</th>

                        <th class="text-right">@lang('cart.price')</th>

                        <th class="text-right">@lang('cart.quantity')</th>

                        <th class="text-right">@lang('cart.subtotal')</th>

                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($objCart as $objItem)
                        <tr>
                            <td>
                                <strong>{{ $objItem->name }}</strong>
                                @if($objItem->options->color != ''), <span class="text-capitalize">{{ $objItem->options->color }}</span>@endif
                                , <span class="text-uppercase">{{ $objItem->options->size }}</span>
                            </td>

                            <td class="text-right">€ {{ number_format($objItem->price, 2, ',', ' ') }}</td>

                            <td class="text-right">{{ $objItem->qty }}</td>

                            <td class="text-right">€ {{ number_format($objItem->subtotal, 2, ',', ' ') }}</td>

                            <td class="text-right"><a href="{{ route('cart.remove', ['id' => $objItem->rowId]) }}" class="text-danger">@fa('times')</a>
                            </td>
                        </tr>
                    @endforeach

                    <tr>
                        <td colspan="3" class="text-right">@lang('cart.shipping')</td>

                        <td class="text-right">€ 1,00</td>

                        <td></td>
                    </tr>

                    <tr class="lead">
                        <td colspan="3" class="text-right">@lang('cart.total')</td>

                        <td class="text-right">€ {{ number_format(Cart::subtotalFloat() + 1, 2, ',', ' ') }}</td>

                        <td></td>
                    </tr>
                    </tbody>
                </table>

                <div class="text-right">
                    <a href="{{ route('products.index') }}" class="btn btn-link btn-lg">@lang('cart.continue')</a>

                    <a href="{{ route('orders.create') }}" class="btn btn-first btn-lg">@lang('cart.create')</a>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/contact.blade.php
@extends('layouts.public')

@section('addCSS')
    {!! htmlScriptTagJsApi() !!}
@endsection

@section('title', 'Contact - ' . config('app.name'))

@section('content')
    <div id="page-content">
        <div class="container pt-2 pt-lg-5 pb-5">
            <h1>@lang('contact.title')</h1>

            <div class="row">
                <div class="col-12 col-lg-6">
                    <img src="https://yasmin-trade.com/images/logos/160x160.png" class="img-fluid d-block mx-auto" alt="Logo">

                    <p class="text-center color-green h2 mt-1">Yasmin Trade s.r.o.</p>

                    <address>
                        Na vŕšku 6

                        <br>

                        811 01, Bratislava

                        <br>

                        Slovak Republic
                    </address>

                    <address>
                        @lang('contact.companyId'): 51 333 147
                    </address>

                    <hr>

                    <address>
                        <strong>@lang('contact.oh')</strong>
                    </address>

                    <address>
                        @fa('envelope') <a href="mailto:fts@yasmin-trade.com">fts@yasmin-trade.com</a>

                        <br>

                        @fa('phone') <a href="tel:+421911415992">+421 911 415 992</a>
                    </address>
                </div>

                <div class="col-12 col-lg-6 pt-5 pt-lg-0">
                    @include('includes/errors')

                    <form action="{{ route('contactPost') }}" method="POST">
                        @csrf

                        <div class="form-group">
                            <label for="name">@lang('contact.name')</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="@lang('contact.name')" maxlength="100" required>
                        </div>

                        <div class="form-group">
                            <label for="email">@lang('contact.email')</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="@lang('contact.email')" maxlength="100" required>
                        </div>

                        <div class="form-group">
                            <label for="message">@lang('contact.message')</label>
                            <textarea class="form-control" id="message" name="message" placeholder="@lang('contact.message')" maxlength="300" rows="4" required></textarea>
                        </div>

                        <div class="recaptcha">
                            {!! htmlFormSnippet() !!}
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-lg btn-first">@lang('contact.send')</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/faq.blade.php
@extends('layouts.public')

@section('title', 'FAQ - ' . config('app.name'))

@section('content')
    <div id="page-content">
        <div class="container pt-2 pt-lg-5 pb-5">
            <h1>@lang('faq.title')</h1>

            <div class="row">
                <div class="col-12 col-lg-6">
                    <p class="text-center big-icon mb-3">@fa('question')</p>

                    <h3 class="color-first">@lang('faq.1')</h3>

                    <p>@lang('faq.1a')</p>

                    <hr class="part">

                    <h3 class="color-first">@lang('faq.2')</h3>

                    <p>@lang('faq.2a')</p>

                    <hr class="part">

                    <h3 class="color-first">@lang('faq.3')</h3>

                    <p>@lang('faq.3a')</p>

                    <hr class="part">

                    <h3 class="color-first">@lang('faq.4')</h3>

                    <p>@lang('faq.4a')</p>

                    <hr class="part">

                    <h3 class="color-first">@lang('faq.5')</h3>

                    <p>@lang('faq.5a')</p>
                </div>

                <div class="col-12 col-lg-6">
                    <p class="text-center big-icon mb-3">@fa('lock')</p>

                    <h3 class="color-first">@lang('faq.6')</h3>

                    <p>@lang('faq.6a')</p>

                    <p><strong><a href="https://www.paypal.com" target="_blank">PayPal</a> @lang('faq.6a4')</strong> @lang('faq.6a2')</p>

                    <p>@lang('faq.6a3') <a href="{{ route('pp') }}">@lang('layout.footer.pp')</a>.</p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.public')

@section('content')
    <div id="page-content">
        <div class="container-fluid">
            <div id="indexPresenter" class="row">
                <div class="col-12 p-0">
                    <div id="mainCarousel" class="carousel slide carousel-fade" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <picture>
                                    <source media="(min-width: 992px)" srcset="{{ mix('images/carousel/3.jpg') }}">
                                    <img src="{{ mix('images/carousel/3s.jpg') }}" class="d-block w-100" alt="">
                                </picture>
                            </div>

                            <div class="carousel-item">
                                <picture>
                                    <source media="(min-width: 992px)" srcset="{{ mix('images/carousel/2.jpg') }}">
                                    <img src="{{ mix('images/carousel/2s.jpg') }}" class="d-block w-100" alt="">
                                </picture>
                            </div>

                            <div class="carousel-item">
                                <picture>
                                    <source media="(min-width: 992px)" srcset="{{ mix('images/carousel/1.jpg') }}">
                                    <img src="{{ mix('images/carousel/1s.jpg') }}" class="d-block w-100" alt="">
                                </picture>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-lg-6 p-0">
                    <div id="old" class="product">
                        <div class="content">
                            <h2 class="font-primary color-first text-shadow mb-0">OLD</h2>

                            <p class="lead d-none d-md-block">I am too OLD For This Shit</p>

                            <a href="{{ route('products.old', ['white', 'm']) }}" class="btn btn-second btn-lg">@lang('index.btn')</a>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-lg-6 p-0">
                    <div id="sober" class="product">
                        <div class="content">
                            <h2 class="font-primary color-second text-shadow mb-0">SOBER</h2>

                            <p class="lead d-none d-md-block">I am too SOBER For This Shit</p>

                            <a href="{{ route('products.sober', ['black', 'm']) }}" class="btn btn-first btn-lg">@lang('index.btn')</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="pt-5 pb-5">
                <h3 class="text-center font-primary">@lang('index.quality')</h3>

                <p class="text-center lead">@lang('index.1') <span class="color-first">@lang('index.2')</span> @lang('index.3')<br>@lang('index.4') <span class="color-first">@lang('index.5')</span>.</p>
            </div>
        </div>
    </div>
@endsection

resources/views/pp.blade.php
@extends('layouts.public')

@section('title', 'Privacy policy - ' . config('app.name'))

@section('content')
    <div id="page-content">
        <div class="container pt-2 pt-lg-5 pb-5">
            <h1>Privacy policy</h1>

            <p>Last updated: 17.9.2019</p>

            <h2 class="color-first">1. Identification information of the online store operator forthisshirt.com</h2>

            <p>The operator of the online store forthisshirt.com is the company Yasmin Trade sro, with its registered office at Na vŕšku 6, 811 01 Bratislava, IČO 51 333 147, registered in the Commercial Register of the District Court Bratislava I, section Sro, insert number 125893 / B, e-mail: fts@yasmin-trade.com, tel. no. +421 911 415 992, which processes personal data under the conditions below.</p>

            <h2 class="color-first">2. The scope of the personal data processed, the purposes for which the personal data are intended and the legal basis for the processing</h2>

            <p>Yasmin Trade s.r.o. respects your privacy. Our goal is to offer you full service, so we need to know some of your personal information. We protect this data from misuse and we guarantee that it will not be disclosed to a third party except for the recipients as defined in point 3 below. This applies to your identification and contact information, which we need in order to conclude and fulfill the order, respectively. for direct marketing, and your purchase data. The provision of the personal data concerned constitutes a binding order. You are not required to provide us with this personal information, but if it is not provided to the full extent described below, we will not be able to send you an order or your personal information. to its proper fulfillment by Yasmin Trade s.r.o.</p>

            <p>In the case of natural persons, these are the following personal data: name and surname, home address, resp. delivery address, phone number and email address. <!--In the case of legal entities or sole traders, these are the following information: business name, address of the registered office or place of business, company ID, VAT number, VAT ID and email address.--></p>

            <p>If you have provided us with personal information, it will only be used for the purpose of:</p>

            <ul>
                <li>properly providing our services to customers, to fulfill the order placed through the online shop between us and you as a customer, before confirming this order to answer your questions regarding the provision of our services and the technical administration necessary for the proper provision of our services at forthisshirt.com, all on the legal basis of the Commercial Code of the Slovak Republic and with your consent.</li>

                <li>marketing purposes if you have registered with forthisshirt.com on the legal basis of your consent as expressed by your registration.</li>
            </ul>

            <h2 class="color-first">3. Recipients of personal data</h2>

            <p>Your personal information may be provided to a third party if it is necessary to complete the order or if you have given your explicit consent to such provision. To process your orders we need your name, surname, address (home / delivery), e-mail and phone number. Your e-mail address serves both as an identifier (for logging in to the customer account) and as a means of communication. As part of order processing, the data is provided to our contracted service providers, such as logistics service provider, transporter, banks, etc.</p>

            <h2 class="color-first">4. Criteria for determining the retention period of personal data</h2>

            <p>We only process your personal data for the duration of the purpose for which we collected your personal data.</p>

            <h2 class="color-first">5. Customer's privacy rights</h2>

            <p>As a data subject, Customer has the right to:</p>

            <ul>
                <li>the right of the operator to request access to his personal data pursuant to Art. 15 of Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of individuals with regard to the processing of personal data and on the free movement of such data and repealing Directive 95/46 / EC (General Data Protection Regulation); of Act no. 18/2018 Coll. on the protection of personal data and on amendments to certain acts (hereinafter referred to as the “Act”);</li>

                <li>the right to rectify personal data by the controller pursuant to Art. 16 of the General Data Protection Regulation and Section 22 of the Act;</li>

                <li>the right to delete personal data within the meaning of Art. 17 of the General Data Protection Regulation and § 23 of the Act;</li>

                <li>the right to limit the processing of personal data within the meaning of Art. 18 of the General Data Protection Regulation and § 24 of the Act;</li>

                <li>the right to object to the processing of personal data by the controller for the purposes of direct marketing, including profiling, in so far as it relates to direct marketing. If a customer objects to the processing of personal data for direct marketing purposes, the controller may not further process the customer's personal data for direct marketing purposes;</li>

                <li>the right to the transfer of the customer's personal data pursuant to Art. 20 of the General Data Protection Regulation and § 26 of the Act;</li>

                <li>the right to revoke consent to the processing of personal data at any time;</li>

                <li>the right to file a petition for the initiation of proceedings with the Office for Personal Data Protection of the Slovak Republic if the customer believes that he / she was directly affected by his / her rights under the General Data Protection Regulation or under the Act.</li>
            </ul>

            <p>These rights can be exercised by the customer at any time</p>

            <ul>
                <li>in writing by sending a letter to the address of the operator's registered office;</li>

                <li>electronically by sending an e-mail to fts@yasmin-trade.com; or</li>

                <li>by telephone at +421 911 415 992</li>
            </ul>

            <h2 class="color-first">6. Cookies</h2>

            <p>Yasmin Trade s.r.o. ("us", "we", or "our") uses cookies on yasmin-trade.com (the
                "Service"). By using the Service, you consent to the use of cookies.</p>

            <p>Our Cookies Policy explains what cookies are, how we use cookies, how third­parties we may
                partner with may use cookies on the Service, your choices regarding cookies and further information
                about cookies.</p>

            <h3>What are cookies</h3>

            <p>Cookies are small pieces of text sent by your web browser by a website you visit. A cookie file is
                stored in your web browser and allows the Service or a third­party to recognize you and make your
                next visit easier and the Service more useful to you.</p>            <p>Cookies can be "persistent" or "session" cookies.</p>

            <h3>How we use cookies</h3>

            <p>When you use and access the Service, we may place a number of cookies files in your web
                browser.</p>

            <p>We use cookies for the following purposes: to enable certain functions of the Service, to provide
                analytics, to store your preferences, to enable advertisements delivery, including behavioral
                advertising.</p>

            <p>We use both session and persistent cookies on the Service and we use different types of cookies to
                run the Service:</p>

            <p>­ Essential cookies. We may use essential cookies to authenticate users and prevent fraudulent use
                of user accounts.</p>

            <p>For the full disclosure section, including all types of cookies (from essentials to advertising
                cookies), create your own Cookies Policy.</p>

            <h3>Third­party cookies</h3>

            <p>In addition to our own cookies, we may also use various third­parties cookies to report usage
                statistics of the Service, deliver advertisements on and through the Service, and so on.</p>

            <p>We use the following third party services: <strong>Google Tag Manager, Google Analytics, Facebook Pixel.</strong></p>

            <h3>What are your choices regarding cookies</h3>

            <p>If you'd like to delete cookies or instruct your web browser to delete or refuse cookies, please visit
                the help pages of your web browser.</p>

            <p>Please note, however, that if you delete cookies or refuse to accept them, you might not be able to
                use all of the features we offer, you may not be able to store your preferences, and some of our
                pages might not display properly.</p>

            <h3>Where can your find more information about cookies</h3>

            <p>You can learn more about cookies and the following third­party websites:</p>

            <ul>
                <li>AllAboutCookies: <a href="http://www.allaboutcookies.org/" target="_blank">http://www.allaboutcookies.org/</a></li>

                <li>Network Advertising Initiative: <a href="https://www.networkadvertising.org/" target="_blank">https://www.networkadvertising.org/</a></li>
            </ul>
        </div>
    </div>
@endsection