routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Public
Route::get('/', 'PublicController@index')->name('index');
Route::get('/brand', 'PublicController@brand')->name('brand');
Route::get('/contact', 'PublicController@contact')->name('contact');
Route::post('/contact', 'PublicPostController@contact')->name('contactPost');
Route::get('/faq', 'PublicController@faq')->name('faq');
Route::get('/privacy-policy', 'PublicController@pp')->name('pp');
Route::get('/terms-and-conditions', 'PublicController@tac')->name('tac');
Route::get('/claims-and-returns', 'PublicController@car')->name('car');

// Cart
Route::prefix('cart')->name('cart.')->group(function() {
    Route::get('/', 'CartController@index')->name('index');
    Route::post('/add', 'CartController@add')->name('add');
    Route::get('/remove/{id}', 'CartController@remove')->name('remove');
});

// Orders
Route::resource('orders', 'OrderController')->only([
    'create', 'store'
]);
Route::get('/orders/{order}/payment', 'OrderController@payment')->name('orders.payment');
Route::get('/orders/{order}/pay/{paypal_id}', 'OrderController@pay')->name('orders.pay');
//Route::get('/orders/{order}/gen', 'OrderController@generateInvoice');

// Products
Route::prefix('products')->name('products.')->group(function() {
    Route::get('/', 'ProductController@index')->name('index');
//    Route::get('/t-shirt/{product}/{color}/{size}', 'ProductController@show')->name('product');
    Route::get('/t-shirt/old/{color}/{size}', 'ProductController@old')->name('old');
    Route::get('/t-shirt/sober/{color}/{size}', 'ProductController@sober')->name('sober');
    Route::get('/t-shirt/set/{size}', 'ProductController@set')->name('set');
});

// Auth, Account & Admin
Auth::routes();
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('fb');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback')->name('fb_callback');

Route::prefix('account')->name('account.')->middleware('auth')->group(function() {
    Route::get('/', 'AccountController@index')->name('index');
    Route::put('/update', 'AccountController@update')->name('update');
    Route::get('/download', 'AccountController@download')->name('download');
    Route::post('/delete', 'AccountController@delete')->name('delete');

    Route::resource('orders', 'OrderController')->only([
        'index', 'show'
    ]);
    Route::get('/orders/{order}/invoice', 'OrderController@invoice')->name('orders.invoice');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'check-admin'])->group(function() {
    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('comments', 'Admin\CommentController')->only([
        'store'
    ]);

    Route::resource('orders', 'Admin\OrderController')->only([
        'index', 'show'
    ]);
    Route::get('/orders/{order}/invoice', 'Admin\OrderController@invoice')->name('orders.invoice');
    Route::put('/orders/{order}/status', 'Admin\OrderController@status')->name('orders.status');

    Route::resource('users', 'Admin\UserController')->only([
        'index', 'show', 'edit', 'update'
    ]);
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model {
    protected $fillable = ['user_id', 'name', 'surname', 'email', 'phone', 'street', 'city', 'zip', 'country', 'note', 'total',
        'paid', 'paypal_order_id', 'paid_at'];

    protected $casts = [
        'total' => 'float',
        'paid' => 'boolean',
        'paid_at' => 'datetime'
    ];

    public function pay($strPayPalOrderId) {
        $this->status = 'paid';
        $this->paid = 1;
        $this->paypal_order_id = $strPayPalOrderId;
        $this->paid_at = date('Y-m-d H:i:s');
    }

    // Accessors
    public function getFullNameAttribute() {
        return $this->name . ' ' . $this->surname;
    }

    public function getAddressAttribute() {
        return $this->street . ', ' . $this->city . ', ' . $this->zip . ', ' . $this->country;
    }

    // Relations
    public function ordered_products() {
        return $this->hasMany(OrderedProduct::class);
    }

    public function comments() {
        return $this->morphMany(Comment::class, 'commentable');
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\Http\Requests\OrderStatusRequest;

class OrderController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $arrOrders = Order::orderBy('id', 'DESC')->paginate(50);

        return view('admin/orders/index')->with([
            'arrOrders' => $arrOrders
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //
    }

    public function show(Order $order) {
        $order->load('comments');

        return view('admin/orders/show')->with([
            'objOrder' => $order
        ]);
    }

    public function invoice(Order $order) {
        return response()->download(storage_path('app/public/invoices/' . $order->id . '.pdf'));
    }

    public function status(Order $order, OrderStatusRequest $objRequest) {
        $order->status = $objRequest->status;
        $order->save();

        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Events\OrderCreated;
use App\Events\OrderPaid;
use ConsoleTVs\Invoices\Classes\Invoice;
use Illuminate\Http\Request;
use Gloudemans\Shoppingcart\Facades\Cart;
use App\Http\Requests\OrderRequest;
use App\Order;
use App\OrderedProduct;
use Auth;
use App\Classes\PayPalClient;
use PayPalCheckoutSdk\Orders\OrdersGetRequest;
use RealRashid\SweetAlert\Facades\Alert;
use DB;

class OrderController extends Controller {
    public function index() {
        $arrOrders = Order::where('user_id', Auth::user()->id)->orderBy('id', 'DESC')->get();

        return view('account/orders/index')->with([
            'arrOrders' => $arrOrders
        ]);
    }

    public function show(Order $order) {
        if (Auth::user()->id != $order->user_id) abort(401);

        $order->load('ordered_products');

        return view('account/orders/show')->with([
            'objOrder' => $order
        ]);
    }

    public function create() {
        return view('orders/create')->with([
            'objCart' => Cart::content()
        ]);
    }

    public function store(OrderRequest $objRequest) {
        $arrOrder = $objRequest->all() + ['total' => Cart::subtotalFloat() + 1];

        if (Auth::check()) $arrOrder['user_id'] = Auth::user()->id;

        $objOrder = DB::transaction(function() use ($arrOrder) {
            $objOrder = Order::create($arrOrder);

            foreach(Cart::content() as $objItem) {
                if ($objItem->options->color == 'white') $color = 1;
                elseif ($objItem->options->color == 'black') $color = 2;
                else $color = null;

                if ($objItem->options->size == 's') $size = 1;
                elseif ($objItem->options->size == 'm') $size = 2;
                else $size = 3;

                OrderedProduct::create([
                    'order_id' => $objOrder->id,
                    'product_id' => $objItem->id,
                    'color_id' => $color,
                    'size_id' => $size,
                    'amount' => $objItem->qty
                ]);
            }

            return $objOrder;
        }, 3);

        $objOrder->load('ordered_products');

        event(new OrderCreated($objOrder));

        Cart::destroy();

        return redirect(route('orders.payment', ['id' => $objOrder->id]));
    }

    public function payment(Order $order) {
        $order->load('ordered_products');

        return view('orders/payment')->with([
            'objOrder' => $order
        ]);
    }

    public function pay(Order $order, $paypal_id) {
        $objOrder = $order->load('ordered_products');
        $response = PayPalClient::client()->execute(new OrdersGetRequest($paypal_id));

        if ($response->result->status != "COMPLETED") {
            Alert::error('Something went wrong!', 'Your payment could not be processed.');

            return back();
        }

        $objOrder->pay($paypal_id);
        $objOrder->save();

        event(new OrderPaid($objOrder));

        Alert::success('Success!', 'Your order was successfully paid.');

        return Auth::check() ? redirect(route('account.orders.show', ['id' => $objOrder->id])) : redirect(route('index'));
    }

    public function invoice(Order $order) {
        if (Auth::user()->id != $order->user_id) abort(401);

        return response()->download(storage_path('app/public/invoices/' . $order->id . '.pdf'));
    }

    public function generateInvoice(Order $order) {
        $objInvoice = Invoice::make();

        foreach ($order->ordered_products as $objProduct) {
            $objInvoice->addItem($objProduct->formattedName, round($objProduct->product->price * 0.8, 2), $objProduct->amount);
        }

        return $objInvoice->addItem('Shipping', 0.8, 1)
            ->number('FTS' . $order->id)
            ->tax($order->total - $objInvoice->subTotalPriceFormatted())
            ->customer([
                'name'      => $order->fullName,
                'location'  => $order->street,
                'zip'       => $order->zip,
                'city'      => $order->city,
                'country'   => $order->country,
            ])
            ->show('public/invoices/'. $order->id . '.pdf');
    }
}

resources/views/admin/orders/index.blade.php
@extends('layouts/admin')

@section('content')
    <div id="page-content" class="admin">
        <div class="container-fluid pt-2 pb-5">
            <h2>Orders <span class="badge badge-dark">{{ $arrOrders->count() }} / {{ $arrOrders->total() }}</span></h2>

            <table class="table table-striped table-bordered">
                <thead>
                <tr class="text-center">
                    <th>Date & time</th>

                    <th>Status</th>

                    <th>Name</th>

                    <th>Address</th>

                    <th>E-mail</th>

                    <th>Phone</th>

                    <th>Price</th>

                    <th></th>
                </tr>
                </thead>

                <tbody>
                    @each('components/admin/orders/order', $arrOrders, 'objOrder')
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/orders/show.blade.php
@extends('layouts/admin')

@section('content')
    <div id="page-content" class="admin">
        <div class="container-fluid pt-2 pb-5">
            <h2>Order #{{ $objOrder->id }}</h2>

            <div class="row">
                <div class="col-12 col-lg-2">
                    <div class="card">
                        <header class="card-header">
                            <h4 class="card-title mb-0">Details</h4>
                        </header>

                        <div class="card-body">
                            <p><strong>Created:</strong> {{ $objOrder->created_at->format('j.n.Y H:i:s') }}</p>

                            <form action="{{ route('admin.orders.status', ['id' => $objOrder->id]) }}" method="POST">
                                @csrf

                                @method('PUT')

                                <div class="input-group">
                                    <select class="form-control" id="status" name="status">
                                        @component('components/admin/orders/statusSelector', ['status' => $objOrder->status])@endcomponent
                                    </select>

                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Save</button>
                                    </div>
                                </div>
                            </form>

                            <hr>

                            <p>
                                <strong>Name:</strong>
                                @if($objOrder->user_id)
                                    <a href="{{ route('admin.users.show', ['id' => $objOrder->user_id]) }}">{{ $objOrder->full_name }}</a>
                                @else
                                    {{ $objOrder->full_name }}
                                @endif
                            </p>

                            <p>
                                <strong>Address:</strong><br>{{ $objOrder->street }}<br>{{ $objOrder->zip }}, {{ $objOrder->city }}<br>{{ $objOrder->country }}
                            </p>

                            <p><strong>E-mail:</strong> <a href="mailto:{{ $objOrder->email }}">{{ $objOrder->email }}</a></p>

                            <p><strong>Phone:</strong> {{ $objOrder->phone }}</p>

                            <p class="mb-0"><strong>Note:</strong> {{ $objOrder->note }}</p>
                        </div>

                        @if($objOrder->paid)
                            <footer class="card-footer">
                                <a href="{{ route('admin.orders.invoice', ['order' => $objOrder->id]) }}" class="btn btn-first btn-block">@fa('download') Download invoice</a>
                            </footer>
                        @endif
                    </div>
                </div>

                <div class="col-12 col-lg-2">
                    <h4>Comments</h4>

                    <form action="{{ route('admin.comments.store') }}" method="POST">
                        @csrf

                        <input type="hidden" name="commentable_id" value="{{ $objOrder->id }}">

                        <input type="hidden" name="commentable_type" value="App\Order">

                        <div class="form-group">
                            <label for="text">Message</label>
                            <textarea class="form-control" id="text" name="text" maxlength="300" rows="2" required></textarea>
                        </div>

                        <button type="submit" class="btn btn-first btn-block">Save</button>
                    </form>

                    @each('components/admin/comments/comment', $objOrder->comments->reverse(), 'objComment')
                </div>

                <div class="col-12 col-lg-8">
                    <h4>Items</h4>

                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr class="text-center">
                            <th>Product</th>

                            <th>Color</th>

                            <th>Size</th>

                            <th>Amount</th>

                            <th>Price per unit</th>

                            <th>Price</th>
                        </tr>
                        </thead>

                        <tbody>
                            @each('components/admin/orders/productItem', $objOrder->ordered_products, 'objItem')

                            <tr class="text-right">
                                <td colspan="5">Shipping</td>

                                <td>&euro; 2,00</td>
                            </tr>

                            <tr class="h4 font-weight-bold text-right">
                                <td colspan="5">Total</td>

                                <td>&euro; {{ number_format($objOrder->total, 2, ',', ' ') }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection