routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Public
Route::get('/', 'PublicController@index')->name('index');
Route::get('/brand', 'PublicController@brand')->name('brand');
Route::get('/contact', 'PublicController@contact')->name('contact');
Route::post('/contact', 'PublicPostController@contact')->name('contactPost');
Route::get('/faq', 'PublicController@faq')->name('faq');
Route::get('/privacy-policy', 'PublicController@pp')->name('pp');
Route::get('/terms-and-conditions', 'PublicController@tac')->name('tac');
Route::get('/claims-and-returns', 'PublicController@car')->name('car');

// Cart
Route::prefix('cart')->name('cart.')->group(function() {
    Route::get('/', 'CartController@index')->name('index');
    Route::post('/add', 'CartController@add')->name('add');
    Route::get('/remove/{id}', 'CartController@remove')->name('remove');
});

// Orders
Route::resource('orders', 'OrderController')->only([
    'create', 'store'
]);
Route::get('/orders/{order}/payment', 'OrderController@payment')->name('orders.payment');
Route::get('/orders/{order}/pay/{paypal_id}', 'OrderController@pay')->name('orders.pay');
//Route::get('/orders/{order}/gen', 'OrderController@generateInvoice');

// Products
Route::prefix('products')->name('products.')->group(function() {
    Route::get('/', 'ProductController@index')->name('index');
//    Route::get('/t-shirt/{product}/{color}/{size}', 'ProductController@show')->name('product');
    Route::get('/t-shirt/old/{color}/{size}', 'ProductController@old')->name('old');
    Route::get('/t-shirt/sober/{color}/{size}', 'ProductController@sober')->name('sober');
    Route::get('/t-shirt/set/{size}', 'ProductController@set')->name('set');
});

// Auth, Account & Admin
Auth::routes();
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('fb');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback')->name('fb_callback');

Route::prefix('account')->name('account.')->middleware('auth')->group(function() {
    Route::get('/', 'AccountController@index')->name('index');
    Route::put('/update', 'AccountController@update')->name('update');
    Route::get('/download', 'AccountController@download')->name('download');
    Route::post('/delete', 'AccountController@delete')->name('delete');

    Route::resource('orders', 'OrderController')->only([
        'index', 'show'
    ]);
    Route::get('/orders/{order}/invoice', 'OrderController@invoice')->name('orders.invoice');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'check-admin'])->group(function() {
    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('comments', 'Admin\CommentController')->only([
        'store'
    ]);

    Route::resource('orders', 'Admin\OrderController')->only([
        'index', 'show'
    ]);
    Route::get('/orders/{order}/invoice', 'Admin\OrderController@invoice')->name('orders.invoice');
    Route::put('/orders/{order}/status', 'Admin\OrderController@status')->name('orders.status');

    Route::resource('users', 'Admin\UserController')->only([
        'index', 'show', 'edit', 'update'
    ]);
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model {
    protected $fillable = ['name', 'slug', 'description', 'price'];

    protected $casts = [
        'price' => 'float'
    ];

    public function getRouteKeyName() {
        return 'slug';
    }

    // Relations
    public function ordered_products() {
        return $this->hasMany(OrderedProduct::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Color;
use App\Size;

class ProductController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('products/index');
    }

    public function old($color = 'black', $size = 'm') {
        return view('products/old')->with([
            'color' => $color,
            'size' => $size
        ]);
    }

    public function sober($color = null, $size = null) {
        return view('products/sober')->with([
            'color' => $color,
            'size' => $size
        ]);
    }

    public function set($size = null) {
        return view('products/set')->with([
            'size' => $size
        ]);
    }

//    /**
//     * Show the form for creating a new resource.
//     *
//     * @return \Illuminate\Http\Response
//     */
//    public function create() {
//        //
//    }
//
//    /**
//     * Store a newly created resource in storage.
//     *
//     * @param \Illuminate\Http\Request $request
//     * @return \Illuminate\Http\Response
//     */
//    public function store(Request $request) {
//        //
//    }

    public function show(Product $product, Color $color, Size $size) {
        return view('products/show')->with([
            'objProduct' => $product,
            'color' => $color,
            'size' => $size
        ]);
    }

//    /**
//     * Show the form for editing the specified resource.
//     *
//     * @param int $id
//     * @return \Illuminate\Http\Response
//     */
//    public function edit($id) {
//        //
//    }
//
//    /**
//     * Update the specified resource in storage.
//     *
//     * @param \Illuminate\Http\Request $request
//     * @param int $id
//     * @return \Illuminate\Http\Response
//     */
//    public function update(Request $request, $id) {
//        //
//    }
//
//    /**
//     * Remove the specified resource from storage.
//     *
//     * @param int $id
//     * @return \Illuminate\Http\Response
//     */
//    public function destroy($id) {
//        //
//    }
}

resources/views/products/index.blade.php
@extends('layouts.public')

@section('title', 'Products - ' . config('app.name'))

@section('content')
    <div id="page-content">
        <div class="container pt-2 pt-lg-5 pb-5">
            <nav class="d-none d-md-block" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">@lang('products/index.home')</a></li>

                    <li class="breadcrumb-item active">@lang('products/index.title')</li>
                </ol>
            </nav>

            <h1>@lang('products/index.title')</h1>

            <div class="row">
                <div class="col-12 col-md-6 col-lg-4 pb-3">
                    <div class="card">
                        <img src="{{ mix('images/tshirts/old/800x600.jpg') }}" class="card-img-top" alt="">

                        <div class="card-body">
                            <p class="h4 mb-0 float-right text-right">
                                &euro; 11,95<br>
                                <span class="badge badge-success text-uppercase">@lang('products/index.inStock')</span>
                            </p>

                            <h3 class="card-title font-primary color-second">T-shirt OLD</h3>

                            <p class="card-text mb-0">@lang('products/index.colors'): <span class="color color-white" data-toggle="tooltip" data-placement="top" title="@lang('products/index.white')"></span></p>

                            <p class="card-text mb-0">@lang('products/index.sizes'): <strong>S, M, L</strong></p>
                        </div>

                        <footer class="card-footer text-right">
                            <a href="{{ route('products.old', ['white', 'm']) }}" class="btn btn-first btn-block">@lang('products/index.details')</a>
                        </footer>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-4 pb-3">
                    <div class="card">
                        <img src="{{ mix('images/tshirts/sober/800x600.jpg') }}" class="card-img-top" alt="">

                        <div class="card-body">
                            <p class="h4 mb-0 float-right text-right">
                                &euro; 11,95<br>
                                <span class="badge badge-success text-uppercase">@lang('products/index.inStock')</span>
                            </p>

                            <h3 class="card-title font-primary color-second">T-shirt SOBER</h3>

                            <p class="card-text mb-0">@lang('products/index.colors'): <span class="color color-black" data-toggle="tooltip" data-placement="top" title="@lang('products/index.black')"></span></p>

                            <p class="card-text mb-0">@lang('products/index.sizes'): <strong>S, M, L</strong></p>
                        </div>

                        <footer class="card-footer text-right">
                            <a href="{{ route('products.sober', ['black', 'm']) }}" class="btn btn-first btn-block">@lang('products/index.details')</a>
                        </footer>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card">
                        <img src="{{ mix('images/tshirts/set/800x600.jpg') }}" class="card-img-top" alt="">

                        <div class="card-body">
                            <p class="h4 mb-0 float-right text-right">
                                &euro; 20,32<br>
                                <span class="text-danger"><small>(@lang('products/index.off', ['percent' => 15]))</small></span><br>
                                <span class="badge badge-success text-uppercase">@lang('products/index.inStock')</span>
                            </p>

                            <h3 class="card-title font-primary color-second">T-shirts set</h3>


                            <p class="card-text mb-0">@lang('products/index.colors'): <span class="color color-white" data-toggle="tooltip" data-placement="top" title="@lang('products/index.white')"></span> + <span class="color color-black" data-toggle="tooltip" data-placement="top" title="@lang('products/index.black')"></span></p>

                            <p class="card-text mb-0">@lang('products/index.sizes'): <strong>S, M, L</strong></p>

                        </div>

                        <footer class="card-footer text-right">
                            <a href="{{ route('products.set', ['m']) }}" class="btn btn-first btn-block">@lang('products/index.details')</a>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/old.blade.php
@extends('layouts.public')

@section('og')
    <meta property="og:title" content="I AM TOO OLD FOR THIS SHIT t-shirt" />
    <meta property="og:description" content="Original sarcastic 100% cotton t-shirt for casual wear" />
    <meta property="og:image" content="{{ config('app.url') }}{{ mix('images/tshirts/old/og.jpg') }}" />
    <meta property="og:url" content="{{ URL::current() }}" />
    <meta property="og:type" content="website" />
    <meta property="fb:app_id" content="1205701956282577" />
@endsection

@section('title', 'T-shirt OLD - ' . config('app.name'))

@section('seo')
    <meta name="keywords" content="t-shirt, shirt, old, sarcasm, joke, gift, fun, meme">
    <meta name="description" content="I AM TOO OLD FOR THIS SHI(R)T t-shirt made of 100% cotton">
@endsection

@section('content')
    <div id="page-content">
        <div id="tshirt-old" class="product-bg">
            <div class="container">
                <nav class="d-none d-md-block" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('index') }}">@lang('products/index.home')</a></li>

                        <li class="breadcrumb-item"><a href="{{ route('products.index') }}">@lang('products/index.title')</a></li>

                        <li class="breadcrumb-item active">T-shirt OLD</li>
                    </ol>
                </nav>

                <div class="row">
                    <div class="col-12 col-md-6 pb-2 pb-lg-0">
                        <a href="{{ mix('images/tshirts/old/1.jpg') }}" data-lightbox="tshirt">
                            <img src="{{ mix('images/tshirts/old/1_800x600.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail" alt="">
                        </a>

                        <div class="row mt-2 mt-lg-4">
                            <div class="col-6">
                                <a href="{{ mix('images/tshirts/old/2.jpg') }}" data-lightbox="tshirt">
                                    <img src="{{ mix('images/tshirts/old/2s.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail" alt="">
                                </a>
                            </div>

                            <div class="col-6">
                                <a href="{{ mix('images/tshirts/old/3.jpg') }}" data-lightbox="tshirt">
                                    <img src="{{ mix('images/tshirts/old/3s.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail" alt="">
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-6">
                        <div class="bg-text color-white p-2 p-lg-4">
                            @include('includes/share_buttons')

                            <h1 class="font-primary color-first text-shadow">T-shirt OLD</h1>

                            <p class="mb-0">
                                <strong>@lang('products/show.gender'):</strong> Unisex

                                <br>

                                <strong>@lang('products/show.material'):</strong> 100 % @lang('products/show.cotton')

                                <br>

                                <strong>@lang('products/show.weight'):</strong> 175 g/m<sup>2</sup>

                                <br>

                                <strong>@lang('products/show.washable'):</strong> 30 °C

                                <br>

                                <span class="badge badge-success">@lang('products/show.inStockLong')</span>
                            </p>

                            <hr>

                            <p class="mb-0">@lang('products/show.size')</p>

                            <div class="list-group list-group-horizontal">
                                <a href="{{ route('products.old', [$color, 's']) }}" class="list-group-item list-group-item-action @if($size == 's') active @endif">S</a>

                                <a href="{{ route('products.old', [$color, 'm']) }}" class="list-group-item list-group-item-action @if($size == 'm') active @endif">M</a>

                                <a href="{{ route('products.old', [$color, 'l']) }}" class="list-group-item list-group-item-action @if($size == 'l') active @endif">L</a>
                            </div>

{{--                            <p class="mt-3 mb-0">Color</p>--}}

{{--                            <div class="list-group list-group-horizontal">--}}
{{--                                <a href="{{ route('products.old', ['black', $size]) }}" class="list-group-item list-group-item-action @if($color == 'black') active @endif">Black</a>--}}

{{--                                <a href="{{ route('products.old', ['white', $size]) }}" class="list-group-item list-group-item-action @if($color == 'white') active @endif">White</a>--}}
{{--                            </div>--}}

                            <div class="row mt-3">
                                <div class="col-12 col-sm-5 col-lg-6">
                                    <p class="mb-0">@lang('products/show.price')</p>

                                    <p class="h3 font-weight-bold mb-0 text-shadow">&euro; 11,95</p>
                                </div>

                                <div class="col-12 col-sm-7 col-lg-6">
                                    <form action="{{ route('cart.add') }}" method="POST">
                                        @csrf

                                        <input type="hidden" name="id" value="1">

                                        <input type="hidden" name="color" value="{{ $color }}">

                                        <input type="hidden" name="size" value="{{ $size }}">

                                        <div class="input-group input-group-lg">
                                            <input type="number" class="form-control" name="quantity" value="1" min="1" step="1" max="10" required>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-first" id="button-addon2">@fa('shopping-cart') @lang('products/show.buy')</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            @include('includes/features')
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container pt-5 pb-5">
            <h2>@lang('products/show.6')</h2>

            <div class="row">
                <div class="col-12 col-md-8">
                    <table class="table table-striped table-bordered text-center">
                        <thead class="thead-dark">
                        <tr>
                            <th>@lang('products/show.size') (cm)</th>

                            <th>S</th>

                            <th>M</th>

                            <th>L</th>
                        </tr>
                        </thead>

                        <tbody>
                        <tr>
                            <td>Height</td>

                            <td>66</td>

                            <td>70</td>

                            <td>74</td>
                        </tr>

                        <tr>
                            <td>Width</td>

                            <td>48</td>

                            <td>52</td>

                            <td>55</td>
                        </tr>
                        </tbody>
                    </table>

                    <p class="text-center color-muted">@lang('products/show.7')</p>
                </div>

                <div class="col-12 col-md-4">
                    <img src="{{ mix('images/tshirts/sizes.jpg') }}" class="img-fluid d-block mx-auto" alt="Sizes">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/set.blade.php
@extends('layouts.public')

@section('og')
    <meta property="og:title" content="OLD & SOBER t-shirts set" />
    <meta property="og:description" content="Original sarcastic 100% cotton t-shirts for casual wear" />
    <meta property="og:image" content="{{ config('app.url') }}{{ mix('images/tshirts/old/og.jpg') }}" />
    <meta property="og:url" content="{{ URL::current() }}" />
    <meta property="og:type" content="website" />
    <meta property="fb:app_id" content="1205701956282577" />
@endsection

@section('title', 'OLD & SOBER t-shirts set - ' . config('app.name'))

@section('seo')
    <meta name="keywords" content="t-shirts, shirts, old, sober, sarcasm, joke, gift, fun, meme">
    <meta name="description" content="OLD & SOBER t-shirts set made of 100% cotton">
@endsection

@section('content')
    <div id="page-content">
        <div id="tshirts-set" class="product-bg">
            <div class="container">
                <nav class="d-none d-md-block" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('index') }}">@lang('products/index.home')</a></li>

                        <li class="breadcrumb-item"><a href="{{ route('products.index') }}">@lang('products/index.title')</a></li>

                        <li class="breadcrumb-item active">T-shirts SET</li>
                    </ol>
                </nav>

                <div class="row">
                    <div class="col-12 col-md-6 pb-2 pb-lg-0">
                        <a href="{{ mix('images/tshirts/set/1.jpg') }}" data-lightbox="tshirt">
                            <img src="{{ mix('images/tshirts/set/1_800x600.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail" alt="">
                        </a>

                        <div class="row mt-2 mt-lg-4">
                            <div class="col-6">
                                <a href="{{ mix('images/tshirts/set/2.jpg') }}" data-lightbox="tshirt">
                                    <img src="{{ mix('images/tshirts/set/2s.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail" alt="">
                                </a>
                            </div>

                            <div class="col-6">
                                <a href="{{ mix('images/tshirts/set/3.jpg') }}" data-lightbox="tshirt">
                                    <img src="{{ mix('images/tshirts/set/3s.jpg') }}" class="img-fluid d-block mx-auto img-thumbnail" alt="">
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-6">
                        <div class="bg-text color-white p-2 p-lg-4">
                            @include('includes/share_buttons')

                            <h1 class="font-primary color-first text-shadow">T-shirts set</h1>

                            <p class="mb-0">
                                <strong>@lang('products/show.gender'):</strong> Unisex

                                <br>

                                <strong>@lang('products/show.material'):</strong> 100 % @lang('products/show.cotton')

                                <br>

                                <strong>@lang('products/show.weight'):</strong> OLD 175 g/m<sup>2</sup>, SOBER 160 g/m<sup>2</sup>

                                <br>

                                <strong>@lang('products/show.washable'):</strong> 30 °C

                                <br>

                                <span class="badge badge-success">@lang('products/show.inStockLong')</span>
                            </p>

                            <hr>

                            <p class="mb-0">@lang('products/show.size')</p>

                            <div class="list-group list-group-horizontal">
                                <a href="{{ route('products.set', ['s']) }}" class="list-group-item list-group-item-action @if($size == 's') active @endif">S</a>

                                <a href="{{ route('products.set', ['m']) }}" class="list-group-item list-group-item-action @if($size == 'm') active @endif">M</a>

                                <a href="{{ route('products.set', ['l']) }}" class="list-group-item list-group-item-action @if($size == 'l') active @endif">L</a>
                            </div>

                            <div class="row mt-3">
                                <div class="col-12 col-sm-5 col-lg-6">
                                    <p class="mb-0">@lang('products/show.price')</p>

                                    <p class="h3 font-weight-bold mb-0 text-shadow">&euro; 20,32 <span class="color-first"><small>(15% off)</small></span></p>
                                </div>

                                <div class="col-12 col-sm-7 col-lg-6">
                                    <form action="{{ route('cart.add') }}" method="POST">
                                        @csrf

                                        <input type="hidden" name="id" value="3">

                                        <input type="hidden" name="size" value="{{ $size }}">

                                        <div class="input-group input-group-lg">
                                            <input type="number" class="form-control" name="quantity" value="1" min="1" step="1" max="10" required>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-first" id="button-addon2">@fa('shopping-cart') @lang('products/show.buy')</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            @include('includes/features')
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container pt-5 pb-5">
            <h2>@lang('products/show.6')</h2>

            <div class="row">
                <div class="col-12 col-md-8">
                    <table class="table table-striped table-bordered text-center">
                        <thead class="thead-dark">
                        <tr>
                            <th>@lang('products/show.size') (cm)</th>

                            <th>S</th>

                            <th>M</th>

                            <th>L</th>
                        </tr>
                        </thead>

                        <tbody>
                        <tr>
                            <td>Height</td>

                            <td>66</td>

                            <td>70</td>

                            <td>74</td>
                        </tr>

                        <tr>
                            <td>Width</td>

                            <td>48</td>

                            <td>52</td>

                            <td>55</td>
                        </tr>
                        </tbody>
                    </table>

                    <p class="text-center color-muted">@lang('products/show.7')</p>
                </div>

                <div class="col-12 col-md-4">
                    <img src="{{ mix('images/tshirts/sizes.jpg') }}" class="img-fluid d-block mx-auto" alt="Sizes">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.public')

@section('title', 'Product - ' . config('app.name'))

@section('content')
    <div id="page-content">

    </div>
@endsection